# Version for this file.
version: 1

# (Optional) List of env variables used during compilation.
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# The OS to compile for. `GOOS` env variable will be set to this value.
goos: 
  - windows
  - linux

# The architecture to compile for. `GOARCH` env variable will be set to this value.
goarch: amd64

# Binary output name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: binary-{{ .Os }}-{{ .Arch }}
